//
//  SparseTests.swift
//  NumericSwiftTests
//
//  Tests for the Sparse module: COO/CSR formats, SpMV, SpMM, element-wise add,
//  transpose, spsolve (CG for SPD, dense-LU fallback for general).
//
//  Oracle source: scipy.sparse / scipy.sparse.linalg (Python venv at /tmp/.nsoracle).
//  All literal expected values were generated by scipy and pasted verbatim.
//
//  Licensed under the Apache License, Version 2.0.
//

import XCTest
@testable import NumericSwift

final class SparseTests: XCTestCase {

    // MARK: - Helpers

    /// Tolerance for floating-point comparisons.
    private let eps = 1e-10

    private func assertVecEqual(_ actual: [Double], _ expected: [Double],
                                 tolerance: Double? = nil,
                                 file: StaticString = #filePath, line: UInt = #line) {
        let tol = tolerance ?? eps
        XCTAssertEqual(actual.count, expected.count, "vector length mismatch",
                       file: file, line: line)
        for (i, (a, e)) in zip(actual, expected).enumerated() {
            XCTAssertEqual(a, e, accuracy: tol,
                           "element [\(i)]: \(a) ≠ \(e)", file: file, line: line)
        }
    }

    private func assertDenseEqual(_ actual: LinAlg.Matrix, _ expected: [[Double]],
                                   tolerance: Double? = nil,
                                   file: StaticString = #filePath, line: UInt = #line) {
        let tol = tolerance ?? eps
        XCTAssertEqual(actual.rows, expected.count,
                       "row count mismatch", file: file, line: line)
        for i in 0..<min(actual.rows, expected.count) {
            XCTAssertEqual(actual.cols, expected[i].count,
                           "col count mismatch at row \(i)", file: file, line: line)
            for j in 0..<min(actual.cols, expected[i].count) {
                XCTAssertEqual(actual[i, j], expected[i][j], accuracy: tol,
                               "[\(i),\(j)]: \(actual[i,j]) ≠ \(expected[i][j])",
                               file: file, line: line)
            }
        }
    }

    // MARK: - COO Construction

    /// Empty (0×0) COO matrix: nnz = 0, shape correct.
    func testCOO_emptyMatrix() throws {
        let m = try Sparse.COOMatrix(rows: 0, cols: 0, triplets: [])
        XCTAssertEqual(m.rows, 0)
        XCTAssertEqual(m.cols, 0)
        XCTAssertEqual(m.nnz, 0)
    }

    /// All-zero matrix (3×3 with no nonzeros).
    func testCOO_allZeroMatrix() throws {
        let m = try Sparse.COOMatrix(rows: 3, cols: 3, triplets: [])
        XCTAssertEqual(m.rows, 3)
        XCTAssertEqual(m.cols, 3)
        XCTAssertEqual(m.nnz, 0)
        let dense = m.toDense()
        assertDenseEqual(dense, [[0, 0, 0], [0, 0, 0], [0, 0, 0]])
    }

    /// Single-nonzero COO construction.
    func testCOO_singleNonzero() throws {
        // scipy: coo_matrix(([5.0], ([2],[3])), shape=(4,5)).toarray()
        // => 4×5 zero matrix with [2,3]=5
        let m = try Sparse.COOMatrix(rows: 4, cols: 5,
                                      triplets: [(row: 2, col: 3, value: 5.0)])
        XCTAssertEqual(m.rows, 4)
        XCTAssertEqual(m.cols, 5)
        XCTAssertEqual(m.nnz, 1)
        let dense = m.toDense()
        XCTAssertEqual(dense[2, 3], 5.0, accuracy: eps)
        XCTAssertEqual(dense[0, 0], 0.0, accuracy: eps)
    }

    /// Duplicate triplets must be SUMMED (scipy.sparse COO semantics).
    /// Oracle: coo_matrix(([1,2,3,4,5], ([0,0,1,1,1],[0,0,1,0,1])), shape=(2,2)).toarray()
    /// => [[3, 0], [4, 8]]
    func testCOO_duplicateTripletsSummed() throws {
        let triplets: [(row: Int, col: Int, value: Double)] = [
            (0, 0, 1.0), (0, 0, 2.0),
            (1, 1, 3.0), (1, 0, 4.0), (1, 1, 5.0)
        ]
        let m = try Sparse.COOMatrix(rows: 2, cols: 2, triplets: triplets)
        // After deduplication: nnz = 3 (unique positions)
        let dense = m.toDense()
        XCTAssertEqual(dense[0, 0], 3.0, accuracy: eps)   // 1+2
        XCTAssertEqual(dense[0, 1], 0.0, accuracy: eps)
        XCTAssertEqual(dense[1, 0], 4.0, accuracy: eps)
        XCTAssertEqual(dense[1, 1], 8.0, accuracy: eps)   // 3+5
    }

    /// Out-of-bounds triplet must throw.
    func testCOO_outOfBoundsThrows() {
        XCTAssertThrowsError(
            try Sparse.COOMatrix(rows: 3, cols: 3,
                                  triplets: [(row: 3, col: 0, value: 1.0)])
        )
        XCTAssertThrowsError(
            try Sparse.COOMatrix(rows: 3, cols: 3,
                                  triplets: [(row: 0, col: 3, value: 1.0)])
        )
        XCTAssertThrowsError(
            try Sparse.COOMatrix(rows: 3, cols: 3,
                                  triplets: [(row: -1, col: 0, value: 1.0)])
        )
    }

    // MARK: - Dense → COO

    /// Round-trip: dense → COO → dense should reproduce the original.
    func testCOO_fromDenseRoundTrip() throws {
        let dense = LinAlg.Matrix([[1.0, 0.0, 0.0],
                                   [0.0, 2.0, 0.0],
                                   [0.0, 0.0, 3.0]])
        let coo = Sparse.COOMatrix(dense)
        // Diagonal: 3 nonzeros
        XCTAssertEqual(coo.nnz, 3)
        let back = coo.toDense()
        assertDenseEqual(back, [[1, 0, 0], [0, 2, 0], [0, 0, 3]])
    }

    /// Dense → COO excludes exact zeros.
    func testCOO_fromDenseExcludesZeros() throws {
        let dense = LinAlg.Matrix([[1.0, 0.0], [0.0, 0.0]])
        let coo = Sparse.COOMatrix(dense)
        XCTAssertEqual(coo.nnz, 1)
    }

    // MARK: - COO → CSR Conversion

    /// COO → CSR conversion correctness (scipy oracle).
    /// Oracle: coo_matrix(([1,4,2,3], ([0,0,1,2],[0,2,1,2])), shape=(3,3)).tocsr()
    /// => indptr=[0,2,3,4], indices=[0,2,1,2], data=[1,4,2,3]
    func testCOO_toCSR_internals() throws {
        let triplets: [(row: Int, col: Int, value: Double)] = [
            (0, 0, 1.0), (1, 1, 2.0), (2, 2, 3.0), (0, 2, 4.0)
        ]
        let coo = try Sparse.COOMatrix(rows: 3, cols: 3, triplets: triplets)
        let csr = coo.toCSR()

        // CSR indptr: row i contains elements [indptr[i], indptr[i+1])
        // Row 0: 2 entries (cols 0 and 2) => indptr[0]=0, indptr[1]=2
        // Row 1: 1 entry  (col  1)        => indptr[2]=3
        // Row 2: 1 entry  (col  2)        => indptr[3]=4
        XCTAssertEqual(csr.indptr, [0, 2, 3, 4])
        // indices sorted within each row
        XCTAssertEqual(csr.indices, [0, 2, 1, 2])
        XCTAssertEqual(csr.data, [1.0, 4.0, 2.0, 3.0])
    }

    /// Single-nonzero CSR (scipy oracle).
    /// single nnz indptr: [0, 0, 0, 1, 1]  (4×5 matrix, nnz at row 2)
    func testCSR_singleNonzero() throws {
        let coo = try Sparse.COOMatrix(rows: 4, cols: 5,
                                        triplets: [(row: 2, col: 3, value: 5.0)])
        let csr = coo.toCSR()
        XCTAssertEqual(csr.indptr, [0, 0, 0, 1, 1])
        XCTAssertEqual(csr.indices, [3])
        XCTAssertEqual(csr.data, [5.0])
        XCTAssertEqual(csr.nnz, 1)
        XCTAssertEqual(csr.rows, 4)
        XCTAssertEqual(csr.cols, 5)
    }

    // MARK: - Dense → CSR Directly

    func testCSR_fromDenseRoundTrip() throws {
        let dense = LinAlg.Matrix([[1.0, 0.0, 4.0],
                                   [0.0, 2.0, 0.0],
                                   [0.0, 0.0, 3.0]])
        let csr = Sparse.CSRMatrix(dense)
        XCTAssertEqual(csr.nnz, 4)
        let back = csr.toDense()
        assertDenseEqual(back, [[1, 0, 4], [0, 2, 0], [0, 0, 3]])
    }

    // MARK: - nnz / shape introspection

    /// SPD matrix nnz (scipy oracle: 7).
    func testCSR_nnzSPD() throws {
        let dense = LinAlg.Matrix([[4.0, 1.0, 0.0],
                                   [1.0, 3.0, 1.0],
                                   [0.0, 1.0, 2.0]])
        let csr = Sparse.CSRMatrix(dense)
        XCTAssertEqual(csr.nnz, 7)
        XCTAssertEqual(csr.rows, 3)
        XCTAssertEqual(csr.cols, 3)
    }

    // MARK: - Diagonal Matrix Round-Trip

    /// Diagonal matrix round-trip (scipy oracle).
    /// diags([1,2,3,4], 0) => 4×4 diagonal
    func testCSR_diagonalRoundTrip() throws {
        let diag = LinAlg.Matrix([[1.0, 0.0, 0.0, 0.0],
                                   [0.0, 2.0, 0.0, 0.0],
                                   [0.0, 0.0, 3.0, 0.0],
                                   [0.0, 0.0, 0.0, 4.0]])
        let csr = Sparse.CSRMatrix(diag)
        XCTAssertEqual(csr.nnz, 4)
        let back = csr.toDense()
        assertDenseEqual(back, [[1,0,0,0],[0,2,0,0],[0,0,3,0],[0,0,0,4]])
    }

    // MARK: - SpMV (sparse matrix–vector product)

    /// Rectangular SpMV: 3×4 @ 4-vector (scipy oracle: [7, 22, 39]).
    func testSpMV_rectangular() throws {
        // A = [[1,0,2,0],[0,3,0,4],[0,0,5,6]]
        let dense = LinAlg.Matrix([[1.0, 0.0, 2.0, 0.0],
                                   [0.0, 3.0, 0.0, 4.0],
                                   [0.0, 0.0, 5.0, 6.0]])
        let csr = Sparse.CSRMatrix(dense)
        let x = [1.0, 2.0, 3.0, 4.0]
        let y = try csr.spmv(x)
        // scipy: [7, 22, 39]
        assertVecEqual(y, [7.0, 22.0, 39.0])
    }

    /// SpMV with all-zero matrix: result must be zero.
    func testSpMV_allZeroMatrix() throws {
        let dense = LinAlg.Matrix([[0.0, 0.0], [0.0, 0.0]])
        let csr = Sparse.CSRMatrix(dense)
        let y = try csr.spmv([1.0, 2.0])
        assertVecEqual(y, [0.0, 0.0])
    }

    /// SpMV dimension mismatch must throw.
    func testSpMV_dimensionMismatchThrows() {
        let dense = LinAlg.Matrix([[1.0, 2.0], [3.0, 4.0]])
        let csr = Sparse.CSRMatrix(dense)
        XCTAssertThrowsError(try csr.spmv([1.0, 2.0, 3.0]))
    }

    // MARK: - SpMM (sparse matrix × dense matrix)

    /// SpMM: 3×3 sparse @ 3×2 dense (scipy oracle: [[11,14],[9,12],[29,38]]).
    func testSpMM_basic() throws {
        // A = [[1,0,2],[0,3,0],[4,0,5]]
        let A = LinAlg.Matrix([[1.0, 0.0, 2.0],
                                [0.0, 3.0, 0.0],
                                [4.0, 0.0, 5.0]])
        let B = LinAlg.Matrix([[1.0, 2.0],
                                [3.0, 4.0],
                                [5.0, 6.0]])
        let csr = Sparse.CSRMatrix(A)
        let C = try csr.spmm(B)
        // scipy: [[11,14],[9,12],[29,38]]
        assertDenseEqual(C, [[11.0, 14.0], [9.0, 12.0], [29.0, 38.0]])
    }

    /// SpMM dimension mismatch must throw.
    func testSpMM_dimensionMismatchThrows() {
        let A = LinAlg.Matrix([[1.0, 2.0], [3.0, 4.0]])
        let B = LinAlg.Matrix([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]])
        let csr = Sparse.CSRMatrix(A)
        XCTAssertThrowsError(try csr.spmm(B))
    }

    // MARK: - Element-Wise Add

    /// Element-wise add of two same-shape CSR matrices (scipy oracle).
    /// A5=[[1,0,2],[0,3,0]], A6=[[0,4,1],[2,0,5]]
    /// scipy: A5+A6 = [[1,4,3],[2,3,5]]
    func testCSR_elementwiseAdd() throws {
        let A5 = Sparse.CSRMatrix(LinAlg.Matrix([[1.0, 0.0, 2.0],
                                                  [0.0, 3.0, 0.0]]))
        let A6 = Sparse.CSRMatrix(LinAlg.Matrix([[0.0, 4.0, 1.0],
                                                  [2.0, 0.0, 5.0]]))
        let sum = try A5.add(A6)
        assertDenseEqual(sum.toDense(), [[1.0, 4.0, 3.0], [2.0, 3.0, 5.0]])
    }

    /// Shape mismatch in element-wise add must throw.
    func testCSR_elementwiseAddShapeMismatchThrows() {
        let A = Sparse.CSRMatrix(LinAlg.Matrix([[1.0, 2.0], [3.0, 4.0]]))
        let B = Sparse.CSRMatrix(LinAlg.Matrix([[1.0, 2.0, 3.0]]))
        XCTAssertThrowsError(try A.add(B))
    }

    // MARK: - Transpose

    /// CSR transpose (scipy oracle: [[1,4],[2,5],[3,6]] for 2×3 input).
    /// A7 = [[1,2,3],[4,5,6]], A7.T = [[1,4],[2,5],[3,6]]
    func testCSR_transpose() throws {
        let A7 = Sparse.CSRMatrix(LinAlg.Matrix([[1.0, 2.0, 3.0],
                                                  [4.0, 5.0, 6.0]]))
        let AT = A7.transpose()
        assertDenseEqual(AT.toDense(), [[1.0, 4.0], [2.0, 5.0], [3.0, 6.0]])
    }

    /// Transpose of all-zero matrix stays all-zero.
    func testCSR_transposeAllZero() {
        let A = Sparse.CSRMatrix(LinAlg.Matrix([[0.0, 0.0, 0.0],
                                                [0.0, 0.0, 0.0]]))
        let AT = A.transpose()
        XCTAssertEqual(AT.rows, 3)
        XCTAssertEqual(AT.cols, 2)
        XCTAssertEqual(AT.nnz, 0)
    }

    // MARK: - spsolve: SPD via Conjugate Gradient

    /// SPD system: Ax=b with CG. Oracle from scipy.sparse.linalg.cg with rtol=1e-12.
    /// A = [[4,1,0],[1,3,1],[0,1,2]], b = [1,2,3]
    /// scipy: x ≈ [0.2222222222, 0.1111111111, 1.4444444444]
    func testSpsolve_SPD_CG() throws {
        let A = Sparse.CSRMatrix(LinAlg.Matrix([[4.0, 1.0, 0.0],
                                                [1.0, 3.0, 1.0],
                                                [0.0, 1.0, 2.0]]))
        let b = [1.0, 2.0, 3.0]
        let x = try Sparse.spsolve(A, b)
        assertVecEqual(x,
                       [0.2222222222222222, 0.11111111111111119, 1.4444444444444444],
                       tolerance: 1e-8)
    }

    // MARK: - spsolve: Non-SPD via Dense LU Fallback

    /// Non-SPD system: general matrix routed to dense LU fallback.
    /// A = [[2,1,0],[1,3,1],[0,1,4]], b = [1,0,2]
    /// scipy spsolve: x ≈ [0.7222, -0.4444, 0.6111]
    func testSpsolve_nonSPD_denseFallback() throws {
        let A = Sparse.CSRMatrix(LinAlg.Matrix([[2.0, 1.0, 0.0],
                                                [1.0, 3.0, 1.0],
                                                [0.0, 1.0, 4.0]]))
        let b = [1.0, 0.0, 2.0]
        let x = try Sparse.spsolve(A, b)
        // scipy oracle: [0.7222222222, -0.4444444444, 0.6111111111]
        assertVecEqual(x,
                       [0.7222222222222222, -0.4444444444444445, 0.6111111111111112],
                       tolerance: 1e-8)
    }

    /// Singular matrix must throw.
    func testSpsolve_singularThrows() {
        let A = Sparse.CSRMatrix(LinAlg.Matrix([[1.0, 2.0],
                                                [2.0, 4.0]]))
        let b = [1.0, 2.0]
        XCTAssertThrowsError(try Sparse.spsolve(A, b))
    }

    /// Non-square matrix must throw.
    func testSpsolve_nonSquareThrows() {
        let A = Sparse.CSRMatrix(LinAlg.Matrix([[1.0, 2.0, 3.0],
                                                [4.0, 5.0, 6.0]]))
        let b = [1.0, 2.0]
        XCTAssertThrowsError(try Sparse.spsolve(A, b))
    }

    /// Dimension mismatch (b.count ≠ A.rows) must throw.
    func testSpsolve_bDimensionMismatchThrows() {
        let A = Sparse.CSRMatrix(LinAlg.Matrix([[1.0, 0.0], [0.0, 1.0]]))
        let b = [1.0, 2.0, 3.0]
        XCTAssertThrowsError(try Sparse.spsolve(A, b))
    }

    // MARK: - Full Round-Trip Dense → COO → CSR → Dense

    /// Full round-trip: random-ish dense → COO → CSR → dense (exact equality).
    func testFullRoundTrip_denseCOOCSRdense() throws {
        let original = LinAlg.Matrix([[5.0, 0.0, 3.0],
                                       [0.0, 0.0, 1.0],
                                       [2.0, 7.0, 0.0]])
        let coo = Sparse.COOMatrix(original)
        let csr = coo.toCSR()
        let back = csr.toDense()
        assertDenseEqual(back, [[5, 0, 3], [0, 0, 1], [2, 7, 0]])
    }
}
